name: Deploy latest packages to npm

on: [workflow_dispatch]

jobs:
  deploy-latest-packages:
    runs-on: ubuntu-latest

    name: Deploy latest packages to NPM
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v3.3.0
        with:
          node-version: 14

      - name: Check if able to publish changes
        run: npm whoami
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
          npx lerna bootstrap --no-ci

      - name: Deploy packages
        run: npx lerna publish from-package --no-push --no-private --no-git-tag-version --no-verify-access --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
