name: Release Please

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "packages/**"

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"

      - uses: GoogleCloudPlatform/release-please-action@v3.2.6
        id: release
        with:
          release-type: node
          package-name: "@plaidypus-dev/eslint-configs"
          path: packages
          monorepo-tags: true

      - name: Deploy all packages
        uses: plaidypus-dev/eslint-config/.github/workflows/deploy-latest-package.yml@main
        with:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: ${{ steps.release.outputs.release_created }}
